spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.174.130:3306/springboot?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    username: root
    password: root
  mvc:
    view:
      prefix: /
      suffix: .jsp

server:
  port: 8081
  servlet:
    context-path: /test

mybatis:
  mapper-locations: classpath:mapper/*.xml
